import { execSync } from 'child_process';
import http from 'http';
import https from 'https';
import { URL } from 'url';
import fs from 'fs';

/**
 * 测速函数：测量请求某个 URL 的响应时间
 */
async function measureLatency(mirrorUrl) {
    const testUrl = new URL('https://github.com/xmake-io/xmake/archive/refs/tags/v2.8.2.tar.gz');
    // 构造加速后的 URL，通常是 mirrorUrl + originalUrl
    // 不同的代理站有不同的拼接规则，这里假设是常见的前缀模式
    const targetUrl = `${mirrorUrl}${testUrl.href}`;

    const start = Date.now();
    return new Promise((resolve) => {
        const client = targetUrl.startsWith('https') ? https : http;

        // 设置一个强制超时的定时器
        const timer = setTimeout(() => {
            req.destroy();
            resolve({ url: mirrorUrl, latency: 9999, status: 408, error: 'Hard Timeout' });
        }, 5000);

        const req = client.get(targetUrl, (res) => {
            res.on('data', () => {});
            res.on('end', () => {
                clearTimeout(timer);
                resolve({ url: mirrorUrl, latency: Date.now() - start, status: res.statusCode });
            });
        });

        req.on('error', (err) => {
            clearTimeout(timer);
            resolve({ url: mirrorUrl, latency: 9999, status: 500, error: err.message });
        });
    });
}

const mirrors = [
    "https://gh.llkk.cc/",
    "https://ghproxy.cn/",
    "https://ghproxy.net/",
    "https://gitproxy.click/",
    "https://github.tbedu.top/",
    "https://github.moeyy.xyz/",
    "https://ghfast.top/",
    "https://v6.gh-proxy.org/",
    "https://v4.gh-proxy.org/",
    "https://gh-proxy.org/",
    "https://cdn.gh-proxy.org/",
    "https://ghfile.geekertao.top/",
    "https://g.blfrp.cn/",
    "https://xiake.pro/"
];

// 解析命令行参数
const args = process.argv.slice(2);
const saveFlag = args.includes('--save');

console.log("正在对节点进行并发测速 (异步即时反馈)... \n");

// 记录已完成的数量
let finishedCount = 0;
const totalCount = mirrors.length;

// 创建带即时反馈的测速任务
const tasks = mirrors.map(async (url) => {
    const result = await measureLatency(url);
    finishedCount++;

    // 即时打印结果，让用户看到“异步”在工作
    const statusIcon = (result.status === 200 || result.status === 302) ? "✅" : "❌";
    const latencyStr = result.latency === 9999 ? "超时" : `${result.latency}ms`;
    console.log(`[${finishedCount}/${totalCount}] ${statusIcon} ${url.padEnd(35)} : ${latencyStr}`);

    return result;
});

// 所有任务完成后打印最终总结
Promise.all(tasks).then(results => {
    const sorted = results
        .filter(r => r.status === 200 || r.status === 302)
        .sort((a, b) => a.latency - b.latency);

    if (sorted.length > 0) {
        const best = sorted[0].url;
        console.log("\n" + "=".repeat(50));
        console.log("🏆 最终测速总结 (从快到慢):");
        sorted.forEach((r, i) => {
            const medal = i === 0 ? "🥇" : i === 1 ? "🥈" : i === 2 ? "🥉" : "  ";
            console.log(`${medal} ${i + 1}. ${r.url.padEnd(35)} : ${r.latency}ms`);
        });
        console.log("=".repeat(50));
        console.log(`\n推荐节点: ${best}`);

        if (saveFlag) {
            const pacContent = `-- pac.lua (Generated by ping_mirrors.mjs)
-- Date: ${new Date().toLocaleString()}
-- Best Mirror: ${best}

function mirror(url)
    if url:find("github.com") then
        return url:gsub("https://github.com/", "${best}")
    end
    return url
end

function main(url, host)
    if host:find("github.com") then
        return true
    end
end
`;
            fs.writeFileSync('pac.lua', pacContent);
            console.log("✅ 已自动生成并保存 pac.lua 文件。运行 'xmake g --proxy_pac=pac.lua' 即可生效。");
        }
    } else {
        console.log("\n未发现可用节点，请检查网络或手动访问 https://xiake.pro/ 获取新节点。");
    }
});
