////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef DEFINE_INTERFACE_BOE7_H
#define DEFINE_INTERFACE_BOE7_H

/***************************************************************************************************
 需要在Algorithm DLL和Algorithm Task之间共享的ENUM,结构体等在此处定义-AVI/SVI/APP共同点
***************************************************************************************************/

#pragma once

#include "Define.h"

//17.09.07-使用Image8bit
#define IMAGE_MAX_GV		256

//17.09.07-Image 12 bit可用(8 bit也可用...浪费内存)
//#define IMAGE_MAX_GV		4096

//17.09.07-Hist->不移交UI(结果不显示Excel)
//使用12bit时...需要很长时间...
#define USE_ALG_HIST		FALSE

//17.11.29-外围信息(AVI&SVI其他工具)
#define USE_ALG_CONTOURS	TRUE

//17.11.29-最大外围信息数量
//18.02.05-SVI不良大小增大/外围数量增加100->500
#define MAX_CONTOURS		500

//////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////

#define WARPING_TARGET_WIDTH 912 // SVI warping size
#define WARPING_TARGET_HEIGHT 513
//[通用]画面ID
//:添加APP照明编号
enum ENUM_IMAGE_CLASSIFY
{
	// AVI
	E_IMAGE_CLASSIFY_AVI_R = 0,	// 00 R		
	E_IMAGE_CLASSIFY_AVI_G,	// 01 G		
	E_IMAGE_CLASSIFY_AVI_B,	// 02 B		
	E_IMAGE_CLASSIFY_AVI_BLACK,	// 03 BLACK	
	E_IMAGE_CLASSIFY_AVI_WHITE,	// 04 WHITE	
	E_IMAGE_CLASSIFY_AVI_GRAY_32,	// 05 GRAY_32	
	E_IMAGE_CLASSIFY_AVI_GRAY_64,	// 06 GRAY_64	
	E_IMAGE_CLASSIFY_AVI_GRAY_87,	// 07 GRAY_87
	E_IMAGE_CLASSIFY_AVI_GRAY_128,	// 08 GRAY_128	
	E_IMAGE_CLASSIFY_AVI_DUST,	// 09 DUST
	E_IMAGE_CLASSIFY_AVI_VTH,	// 10 VTH
	E_IMAGE_CLASSIFY_AVI_PCD,	// 11 PCD
	E_IMAGE_CLASSIFY_AVI_VINIT,	// 12 VINIT
	E_IMAGE_CLASSIFY_AVI_DUSTDOWN,//13 新增DustDown画面 hjf

	E_IMAGE_CLASSIFY_AVI_COUNT,	// 13 AVI Total

	//////////////////////////////////////////////////////////////////////////

		//18.02.07-如果只有AVI Dust在顶部,则使用相同
	// SVI
	E_IMAGE_CLASSIFY_SVI_R = 0,	// 00 R
	E_IMAGE_CLASSIFY_SVI_G,	// 01 G
	E_IMAGE_CLASSIFY_SVI_B,	// 02 B
	E_IMAGE_CLASSIFY_SVI_BLACK,	// 03 BLACK
	E_IMAGE_CLASSIFY_SVI_WHITE,	// 04 WHITE	
	E_IMAGE_CLASSIFY_SVI_GRAY_32,	// 06 GRAY_32
	E_IMAGE_CLASSIFY_SVI_GRAY_64,	// 07 GRAY_64
	E_IMAGE_CLASSIFY_SVI_GRAY_87,	// 08 GRAY_87
	E_IMAGE_CLASSIFY_SVI_GRAY_128,	// 09 GRAY_128

	E_IMAGE_CLASSIFY_SVI_COUNT,	// 09 SVI Total

	//////////////////////////////////////////////////////////////////////////

	// APP
	E_IMAGE_CLASSIFY_APP_ALL = 0,	//00APP All Illum			整体照明值20		
	E_IMAGE_CLASSIFY_APP_RIGHT,	// 01 APP Right Illum 2
	E_IMAGE_CLASSIFY_APP_LEFT,	// 02 APP Left Illum 
	E_IMAGE_CLASSIFY_APP_BOTTOM,	// 03 APP Bottom Illum 
	E_IMAGE_CLASSIFY_APP_TOP,	// 04 APP Top Illum 
	E_IMAGE_CLASSIFY_APP_ALL2,	//05 APP All Illum		整体照明值70
	E_IMAGE_CLASSIFY_APP_DUST,	// 06 APP dust Illum

	E_IMAGE_CLASSIFY_APP_COUNT		// 07 Total
};

//方向更改为AVI/SVI/APP公共

enum ENUM_ALIGN_TYPE
{
	E_ALIGN_TYPE_LEFT = 0,
	E_ALIGN_TYPE_TOP,
	E_ALIGN_TYPE_RIGHT,
	E_ALIGN_TYPE_BOTTOM,
	E_ALIGN_TYPE_END
};

//:在GUI中,将AVL,ABI集成到一个XML文件中,并将Algorithm集成到一个XML文件中
//[AVI通用]错误判定结果
//17.03.09新增不良项目
enum ENUM_DEFECT_JUDGEMENT
{
	//////////////////////////////////////////////////////////////////////////
		//AVI故障-显示异常
	//////////////////////////////////////////////////////////////////////////

		//启动显示异常
	E_DEFECT_JUDGEMENT_DISPLAY_ABNORMAL_START = 0,

	E_DEFECT_JUDGEMENT_DISPLAY_ABNORMAL = E_DEFECT_JUDGEMENT_DISPLAY_ABNORMAL_START,	//点灯以上
	E_DEFECT_JUDGEMENT_DISPLAY_OFF,	//完全不能点灯(环境不良&Cell以上)
	E_DEFECT_JUDGEMENT_DISPLAY_DARK,	//点灯亮暗
	E_DEFECT_JUDGEMENT_DISPLAY_BRIGHT,	//点灯亮度亮度	
	E_DEFECT_JUDGEMENT_DISPLAY_CHOLE_ABNORMAL,	//CHole环境亮度异常
	E_DEFECT_JUDGEMENT_DUST_GROUP,	//组性悬浮物

	E_DEFECT_JUDGEMENT_DUST_DOWN,
	//显示以上结束
	E_DEFECT_JUDGEMENT_DISPLAY_ABNORMAL_END = E_DEFECT_JUDGEMENT_DUST_DOWN,

	//////////////////////////////////////////////////////////////////////////
		//AVI不良-Point不良
	//////////////////////////////////////////////////////////////////////////

		//Point错误开始
	E_DEFECT_JUDGEMENT_POINT_START,

	E_DEFECT_JUDGEMENT_POINT_DARK = E_DEFECT_JUDGEMENT_POINT_START,	//暗点
	E_DEFECT_JUDGEMENT_POINT_BRIGHT,	//名店
	E_DEFECT_JUDGEMENT_POINT_WEAK_BRIGHT,	//简明点
	E_DEFECT_JUDGEMENT_POINT_BRIGHT_DARK,	//名/暗点
	E_DEFECT_JUDGEMENT_POINT_DARK_SP_1,	//Red Pattern暗点
	E_DEFECT_JUDGEMENT_POINT_DARK_SP_2,	//Green Pattern暗点
	E_DEFECT_JUDGEMENT_POINT_DARK_SP_3,	//Blue Pattern暗点
	E_DEFECT_JUDGEMENT_POINT_GROUP_DARK,	//行李暗点
	E_DEFECT_JUDGEMENT_POINT_GROUP_BRIGHT,	//群集名点
	E_DEFECT_JUDGEMENT_POINT_DIMPLE,   // DIMPLE


	E_DEFECT_JUDGEMENT_POINT_DUSTDOWN,

	E_DEFECT_JUDGEMENT_POINT_BRIGHT_1,
	E_DEFECT_JUDGEMENT_POINT_BRIGHT_2,

	E_DEFECT_JUDGEMENT_POINT_CELL_PARTICLE,
	E_DEFECT_JUDGEMENT_POINT_CELL_PARTICLE_1,
	E_DEFECT_JUDGEMENT_POINT_CELL_PARTICLE_2,
	//Point不良结束 
	//2024.7.9 新增judge  需要在DEFITEM_LIST.xml修改后使用 暂未修改judge项索引  hjf 
	E_DEFECT_JUDGEMENT_POINT_END = E_DEFECT_JUDGEMENT_POINT_CELL_PARTICLE_2,

	//////////////////////////////////////////////////////////////////////////
		//AVI不良-Line不良
	//////////////////////////////////////////////////////////////////////////

		//线路开始不良
	E_DEFECT_JUDGEMENT_LINE_START,

	E_DEFECT_JUDGEMENT_LINE_X_BRIGHT = E_DEFECT_JUDGEMENT_LINE_START,	//亮X射线
	E_DEFECT_JUDGEMENT_LINE_X_BRIGHT_MULT,   //亮X兰人束
	E_DEFECT_JUDGEMENT_LINE_Y_BRIGHT,	//亮Y线
	E_DEFECT_JUDGEMENT_LINE_Y_BRIGHT_MULT,   //明亮的Y形线束
	E_DEFECT_JUDGEMENT_LINE_X_DARK,	//暗X射线
	E_DEFECT_JUDGEMENT_LINE_X_DARK_MULT,	//暗X射线束
	E_DEFECT_JUDGEMENT_LINE_Y_DARK,	//暗Y线
	E_DEFECT_JUDGEMENT_LINE_Y_DARK_MULT,	//暗Y线束
	E_DEFECT_JUDGEMENT_LINE_X_OPEN,	//短X射线
	E_DEFECT_JUDGEMENT_LINE_Y_OPEN_RIGHT,	//右边长度短的Y型线	
	E_DEFECT_JUDGEMENT_LINE_Y_OPEN_LEFT,//左边长度较短的Y线
	E_DEFECT_JUDGEMENT_LINE_DGS,//X,Y同时存在
	E_DEFECT_JUDGEMENT_LINE_DGS_X,//X,Y同时存在
	E_DEFECT_JUDGEMENT_LINE_DGS_Y,//X,Y同时存在
	E_DEFECT_JUDGEMENT_XLINE_SPOT,//在X线上Point
	E_DEFECT_JUDGEMENT_YLINE_SPOT,//Y线上Point
	E_DEFECT_JUDGEMENT_LINE_X_EDGE_BRIGHT,//EDGE中的亮X LINE
	E_DEFECT_JUDGEMENT_LINE_Y_EDGE_BRIGHT,//EDGE中的亮Y LINE
	E_DEFECT_JUDGEMENT_LINE_CRACK_RIGHT,//Crack Pattern中的右侧Crack Line
	E_DEFECT_JUDGEMENT_LINE_CRACK_LEFT,//Crack Pattern中的左侧Crack Line
	E_DEFECT_JUDGEMENT_LINE_CRACK_BOTH,//Crack Pattern中的两条Crack Line
	E_DEFECT_JUDGEMENT_LINE_X_DEFECT_BRIGHT,//明亮的MURA星X LINE DEFECT
	E_DEFECT_JUDGEMENT_LINE_Y_DEFECT_BRIGHT,//明亮的MURA星Y LINE DEFECT
	E_DEFECT_JUDGEMENT_LINE_X_DEFECT_DARK,//暗MURA星LINE DEFECT
	E_DEFECT_JUDGEMENT_LINE_Y_DEFECT_DARK,//暗MURA星LINE DEFECT
	E_DEFECT_JUDGEMENT_LINE_PCD_CRACK,//5.99固定位置BLACK,RED,BLUE PATTERN中出现的问题
	E_DEFECT_JUDGEMENT_LINE_X_VTH_BRIGHT,//Special PATTERN亮X线不良
	E_DEFECT_JUDGEMENT_LINE_Y_VTH_BRIGHT,//Special PATTERN亮Y线不良
	E_DEFECT_JUDGEMENT_LINE_X_VTH_DARK,//Special PATTERN暗X线不良
	E_DEFECT_JUDGEMENT_LINE_Y_VTH_DARK,//Special PATTERN暗Y线不良
	E_DEFECT_JUDGEMENT_LINE_X_VTH_DEFECT_BRIGHT,//Special PATTERN亮X线不良
	E_DEFECT_JUDGEMENT_LINE_Y_VTH_DEFECT_BRIGHT,//Special PATTERN亮Y线不良
	E_DEFECT_JUDGEMENT_LINE_X_VTH_DEFECT_DARK,//Special PATTERN暗X线不良
	E_DEFECT_JUDGEMENT_LINE_Y_VTH_DEFECT_DARK,//Special PATTERN暗Y线不良
	E_DEFECT_JUDGEMENT_LINE_VTH_DGS,//Special PATTERN DGS不良
	E_DEFECT_JUDGEMENT_LINE_VTH_DGS_X,//Special PATTERN DGS X线路故障
	E_DEFECT_JUDGEMENT_LINE_VTH_DGS_Y,//Special PATTERN DGS Y线路故障
	E_DEFECT_JUDGEMENT_LINE_ETC_4,	// LINE DEFECT BUFFER4
	E_DEFECT_JUDGEMENT_MURANORMAL_TYPE2_F_GRADE,	// LINE DEFECT BUFFER5
	E_DEFECT_JUDGEMENT_MURANORMAL_TYPE3_F_GRADE,	// LINE DEFECT BUFFER6

	//线路不良结束
	E_DEFECT_JUDGEMENT_LINE_END = E_DEFECT_JUDGEMENT_MURANORMAL_TYPE3_F_GRADE,

	//////////////////////////////////////////////////////////////////////////
		//AVI&SVI不良-Mura不良
	//////////////////////////////////////////////////////////////////////////

		//Mura开始不好
	E_DEFECT_JUDGEMENT_MURA_START,

	E_DEFECT_JUDGEMENT_MURA_MULT_BP = E_DEFECT_JUDGEMENT_MURA_START,//点不良灰色图案接近(100点相似)
	E_DEFECT_JUDGEMENT_MURA_BLACK_SPOT,//点暗点
	E_DEFECT_JUDGEMENT_MURA_WHITE_SPOT,//站点名点
	E_DEFECT_JUDGEMENT_MURA_CORNER_CM,//拐角混色
	E_DEFECT_JUDGEMENT_MURA_UP_CM,//上下混色
	E_DEFECT_JUDGEMENT_MURA_FINGER_CM,//手指混色
	E_DEFECT_JUDGEMENT_MURA_LINE_X,//祖村
	E_DEFECT_JUDGEMENT_MURA_LINE_Y,//祖村
	E_DEFECT_JUDGEMENT_MURA_WHITE,//白村
	E_DEFECT_JUDGEMENT_MURA_CLOUD,	// 
	E_DEFECT_JUDGEMENT_MURA_E_WHITE_SPOT,//下部拍摄
	E_DEFECT_JUDGEMENT_MURA_TYPE4,	// Tpye4 Mura Test
	E_DEFECT_JUDGEMENT_MURA_TYPE3_SMALL,//类型3小污染物
	E_DEFECT_JUDGEMENT_MURA_TYPE3_BIG,//类型3大污染物
	E_DEFECT_JUDGEMENT_MURA_TYPE3_RING,	// Type3 Ring Mura
	E_DEFECT_JUDGEMENT_MURA_TEMP7,
	E_DEFECT_JUDGEMENT_MURA_TEMP8,
	E_DEFECT_JUDGEMENT_MURA_EMP,	// EMP
	E_DEFECT_JUDGEMENT_MURA_EMD_BRIGHT,	// EMD
	E_DEFECT_JUDGEMENT_MURA_EMD_DARK,	// EMD
	E_DEFECT_JUDGEMENT_MURA_BN_CORNER,//拐角触击
	E_DEFECT_JUDGEMENT_MURA_STAMPED,//下部拍摄
	E_DEFECT_JUDGEMENT_MURA_NUGI,//漏气
	E_DEFECT_JUDGEMENT_MURA_EDGE_NUGI,//保持边缘
	E_DEFECT_JUDGEMENT_MURA_EDGE_NUGI_,//保持边缘
	E_DEFECT_JUDGEMENT_MURA_AMORPH_BRIGHT,//明亮的无定形
	E_DEFECT_JUDGEMENT_MURA_AMORPH_DARK,//暗无定形
	E_DEFECT_JUDGEMENT_MURA_AMORPH_SMALL_DARK,	// 
	E_DEFECT_JUDGEMENT_MURA_BOX_SCRATCH,	//
	E_DEFECT_JUDGEMENT_MURA_CM,//混色(使用SVI)
	E_DEFECT_JUDGEMENT_MURA_LINEMURA_X,	// G64 TYPE2 XLINE
	E_DEFECT_JUDGEMENT_MURA_LINEMURA_Y,	// G64 TYPE2 YLINE
	E_DEFECT_JUDGEMENT_MURA_TYPE1MURA_X,	// G64 TYPE1 XLINE
	E_DEFECT_JUDGEMENT_MURA_TYPE1MURA_Y,	// G64 TYPE1 YLINE
	E_DEFECT_JUDGEMENT_MURANORMAL_NOTCH_DEFECT,

	E_DEFECT_JUDGEMENT_PS_MURA,
	E_DEFECT_JUDGEMENT_ZARA,
	E_DEFECT_JUDGEMENT_DENSE_ZARA,
	E_DEFECT_JUDGEMENT_PS_MURA_1,
	E_DEFECT_JUDGEMENT_PS_MURA_MAX,

	E_DEFECT_JUDGEMENT_MURA_WHITE_GAP,
	E_DEFECT_JUDGEMENT_MURA_BLACK_GAP,
		//Mura不良结局
	//2024.7.9 新增judge  需要在DEFITEM_LIST.xml修改后使用 暂未修改judge项索引  hjf 
	E_DEFECT_JUDGEMENT_MURA_END = E_DEFECT_JUDGEMENT_MURA_BLACK_GAP,
	//////////////////////////////////////////////////////////////////////////
		//AVI不良-不要使用Bin2术语->修复ReTest
	//////////////////////////////////////////////////////////////////////////

		//ReTest开始不良
	E_DEFECT_JUDGEMENT_RETEST_START,

	E_DEFECT_JUDGEMENT_RETEST_POINT_DARK = E_DEFECT_JUDGEMENT_RETEST_START,//ReTest评分
	E_DEFECT_JUDGEMENT_RETEST_POINT_BRIGHT,//ReTest暗点Point
	E_DEFECT_JUDGEMENT_RETEST_LINE_BRIGHT,//ReTest亮线
	E_DEFECT_JUDGEMENT_RETEST_LINE_DARK,//ReTest暗线
	E_DEFECT_JUDGEMENT_RETEST_MURA,//ReTest村
	E_DEFECT_JUDGEMENT_RETEST_MURA_BRIGHT,//ReTest亮村

	//ReTest不良结束
	E_DEFECT_JUDGEMENT_RETEST_END = E_DEFECT_JUDGEMENT_RETEST_MURA_BRIGHT,

	//////////////////////////////////////////////////////////////////////////
		//APP相关不良
	//////////////////////////////////////////////////////////////////////////

		//APP启动不良
	E_DEFECT_JUDGEMENT_APP_START,

	E_DEFECT_JUDGEMENT_APP_CUTTING = E_DEFECT_JUDGEMENT_APP_START,	// Cutting  
	E_DEFECT_JUDGEMENT_APP_CUT_C_COME_OUT,//C-Cut伸出项
	E_DEFECT_JUDGEMENT_APP_CUT_C_COME_IN,//失败
	E_DEFECT_JUDGEMENT_APP_MEASURE,
	E_DEFECT_JUDGEMENT_APP_PAD_BURNT,
	E_DEFECT_JUDGEMENT_APP_PAD_SCRATCH,
	E_DEFECT_JUDGEMENT_APP_PAD_DUST,
	E_DEFECT_JUDGEMENT_APP_ACTIVE_BUBBLE,
	E_DEFECT_JUDGEMENT_APP_ACTIVE_SUBSTANCE,
	E_DEFECT_JUDGEMENT_APP_ACTIVE_BUBBLESUBSTANCE,
	E_DEFECT_JUDGEMENT_APP_ACTIVE_SCRATCH,
	E_DEFECT_JUDGEMENT_APP_ACTIVE_MURA,
	E_DEFECT_JUDGEMENT_APP_ACTIVE_HILL,
	E_DEFECT_JUDGEMENT_APP_ACTIVE_FILM_PEELING,
	E_DEFECT_JUDGEMENT_APP_ACTIVE_DUST,
	E_DEFECT_JUDGEMENT_APP_CURL,

	//添加Chole Point相关
	E_DEFECT_JUDGEMENT_POINT_RGB_DARK,
	E_DEFECT_JUDGEMENT_POINT_RGB_BRIGHT,
	E_DEFECT_JUDGEMENT_POINT_CHOLE_DARK,
	E_DEFECT_JUDGEMENT_POINT_CHOLE_BRIGHT,

	//APP不良结束
	E_DEFECT_JUDGEMENT_APP_END = E_DEFECT_JUDGEMENT_POINT_CHOLE_BRIGHT,

	//////////////////////////////////////////////////////////////////////////
	//AI DefectTypeName
	//E_DEFECT_JUDGEMENT_AI_START,
	//E_DEFECT_JUDGEMENT_AI_NG1 = E_DEFECT_JUDGEMENT_AI_START,
	//E_DEFECT_JUDGEMENT_AI_NG2,
	//E_DEFECT_JUDGEMENT_AI_NG3,
	//E_DEFECT_JUDGEMENT_AI_NG4,

	E_DEFECT_JUDGEMENT_COUNT//总数
};

enum ENUM_PANEL_DEFECT_TREND
{
	E_DEFECT_BP_PLUS_DP = E_DEFECT_JUDGEMENT_COUNT,
	E_DEFECT_BP_DP_WB_BD_GD_GB_PLUS,
	E_DEFECT_RETEST,
	E_DEFECT_BP_WB_GB,

	E_PANEL_DEFECT_TREND_COUNT//总数
};

enum ENUM_ALGORITHM_NUM
{
	E_ALGORITHM_POINT = 0,	// 00 POINT	
	E_ALGORITHM_LINE,	// 01 LINE	
	E_ALGORITHM_MURA,	// 02 MURA
	E_ALGORITHM_MURA2,	// 03 RESERVE00
	E_ALGORITHM_MURA3,
	E_ALGORITHM_MURA4,
	E_ALGORITHM_MURA_CHOLE,	//
	E_ALGORITHM_MURA_SCRATCH,	//
	E_ALGORITHM_SVI,	// 04 RESERVE01
	E_ALGORITHM_MURA_NORMAL,	// 05 RESERVE00
	E_ALGORITHM_DUST,	// 新增背光除尘算法 hjf
	E_ALGORITHM_RESERVE05,	// 07 RESERVE05
	E_ALGORITHM_RESERVE06,	// 08 RESERVE06
	E_ALGORITHM_RESERVE07,	// 09 RESERVE07
	E_ALGORITHM_RESERVE08,	// 10 RESERVE08
	E_ALGORITHM_RESERVE09,	// 11 RESERVE09
	E_ALGORITHM_RESERVE10,	// 12 RESERVE10
	E_ALGORITHM_RESERVE11,	// 13 RESERVE11
	E_ALGORITHM_RESERVE12,	// 14 RESERVE12
	E_ALGORITHM_NUMBER				// 15 Total
};

//17.09.26-参数整理
enum ENUM_PARA_COMMON
{
	E_PARA_COMMON_MAX_DEFECT_COUNT,//00:最大不良数量(小于MAX_DEFECT_COUNT)
	E_PARA_COMMON_IMAGE_SAVE_FLAG,//01:算法中间结果Image Save flag
	E_PARA_COMMON_IMAGE_SAVE_COUNT,//02:画面存储顺序计数(Point的函数分为两个)
	E_PARA_COMMON_ALG_IMAGE_NUMBER,//03:当前Alg画面号码
	E_PARA_COMMON_CAMERA_NUMBER,//04:Cam Number(相机编号/SVI)
	E_PARA_COMMON_ROI_NUMBER,//05:ROI Number(ROI编号)
	E_PARA_COMMON_ALG_NUMBER,//06:算法编号(nAlgorithmNumber_)
	E_PARA_COMMON_THREAD_ID,	// 07 : Thread ID
	E_PARA_COMMON_DRAW_DEFECT_NUM_FLAG,//08:Draw Defect Num显示
	E_PARA_COMMON_DRAW_DUST_FLAG,//09:Draw Dust显示(点算法必须旋转)
	E_PARA_COMMON_UI_IMAGE_NUMBER,//10:UI上的模式顺序画面编号
	E_PARA_COMMON_ROTATE_ANGLE,//11:Cell旋转角度(Align计算值,小数点仅为3位...)
	E_PARA_COMMON_ROTATE_CENTER_X,//12:Cell旋转中心x坐标
	E_PARA_COMMON_ROTATE_CENTER_Y,//13:Cell旋转中心y坐标
	E_PARA_COMMON_PS_MODE,//14:图像比例(Pixel Shift Mode-1:None,2:4-Shot,3:9-Shot)
	E_PARA_COMMON_BLOCK_X,	//分区X行
	E_PARA_COMMON_BLOCK_Y,	//分区Y列
	E_PARA_COMMON_TOTAL_COUNT				// Total
};

//整理AVI&APP ALIGN参数
enum ENUM_PARA_ALIGN
{
	///////////////////////////// AVI

		//与AD GV相关(亮度检查)
	E_PARA_CHECK_MIN_GV = 0,//模式平均GV最小亮度
	E_PARA_CHECK_MAX_GV,//模式平均GV最大亮度
	E_PARA_CHECK_AVG_GV,//按模式调整的亮度
	E_PARA_CHECK_AREA_FLAG,//面积确认Flag
	E_PARA_CHECK_AREA_GV,//设置的GV以上面积
	E_PARA_CHECK_AREA_RATIO,//如果在点亮区域中的设置比率高于AD
	E_PARA_CHECK_NON_DEL_FLAG,//删除非检查区域后,AD检查(使用Dust模式X)
	E_PARA_CHECK_NON_DEL_OFFSET,//通过扩大非检查区域删除
	E_PARA_CHECK_PG_FRINGE_MEANGV,//根据均值判断刘海区域异显 hjf
	E_PARA_CHECK_PG_FRINGE_AREA,//根据低于均值的面积判断刘海区域异显 hjf
	E_PARA_CHECK_PATTERN_LABEL,	// Label Check

	//////////////////////////////////////////////////////////////////////////

		//AD相关
	E_PARA_AD_TEXT = 0,//显示文本
	E_PARA_AD_IMAGE_NUM,//AD要检查的模式号(E_IMAGE_CLASSIFY_AVI_WHITE:4)
	E_PARA_AD_RATE,//匹配率(如果禁用:0)
	E_PARA_AD_ZOOM,//画面缩放比例
	E_PARA_AD_MIN_GV,//最小平均GV
	E_PARA_AD_MAX_GV,//最大平均GV
	E_PARA_AD_MAX_STD,//最大标准偏差
	E_PARA_AD_Y_LINE,//垂直行数
	E_PARA_AD_BLOCK_X_GV,//横向GV差异
	E_PARA_AD_BLOCK_X_AREA,//横向面积比
	E_PARA_AD_BLOCK_Y_GV,//纵向GV差
	E_PARA_AD_BLOCK_Y_AREA,//纵向面积比

	// Size
	E_PARA_CELL_SIZE_TEXT,//显示文本
	E_PARA_CELL_SIZE_X,//画面中的Cell宽度(pixel)
	E_PARA_CELL_SIZE_Y,//画面中的Cell垂直长度(pixel)

	//Round Cell相关
	E_PARA_ROUND_TEXT,//显示文本
	E_PARA_ROUND_SETTING,//设置标志
	E_PARA_ROUND_AUTO,   // Auto find round contours
	E_PARA_ROUND_USE,//使用Round拐角处查找算法有/无
	E_PARA_ROUND_IN,//Round拐角处内侧排除检查区域
	E_PARA_ROUND_FIND_OFFSET,//设置Round区域查找范围(上,下,左,右)
	E_PARA_ROUND_DUST_MIN_GV,//Dust模式-填充轮廓平均时设置最小平均GV
	E_PARA_ROUND_OTHER_MIN_GV,//非Dust模式-填充轮廓平均时,设置最小平均GV

	//关于Camera Hole
	E_PARA_CHOLE_TEXT,//显示文本
	E_PARA_CHOLE_SETTING,//设置标志
	E_PARA_CHOLE_USE,//查找CHole的算法ON/OFF
	E_PARA_CHOLE_IN,//CHole外部排除检查区域
	E_PARA_CHOLE_FIND_OFFSET,//设置CHole区域查找范围(上,下,左,右)
	E_PARA_CHOLE_ROI_MIN_GV,//点亮模式-确认CHole ROI最小GV
	E_PARA_CHOLE_SMALL_DEFECT_SIZE,//限制小的不良Judgement不良大小
	E_PARA_CHOLE_SMALL_DEFECT_OFFSET,//小的不良判断消除区域Offset
	E_PARA_CHOLE_BIG_DEFECT_OFFSET,//清除大的不良判断区域Offset
	E_PARA_CHOLE_LINE_DELETE_FLAG,//删除弱视认性线条Defect Flag(对于不出现村坏的模型,该功能OFF)

	E_PARA_CHOLE_POINT_TEXT,//显示文本
	E_PARA_CHOLE_POINT_USE,//设置标志
	E_PARA_CHOLE_POINT_SETTING,//设置标志

	//SHIFT Copy相关
	E_PARA_SHIFT_COPY_TEXT,//显示文本
	E_PARA_SHIFT_COPY_R,//x方向？Pixel移动
	E_PARA_SHIFT_COPY_G,//y方向？Pixel移动
	E_PARA_SHIFT_COPY_B,//x方向重复次数

	//Align相关
	E_PARA_ALIGN_TEXT,//显示文本
	E_PARA_ALIGN_THRESHOLD,//二进制
	E_PARA_ALIGN_MORP,//用于填充Cell之间的空格
	E_PARA_ALIGN_ANGLE_ERR,//超出该范围时发生中警报
	E_PARA_ALIGN_ANGLE_WAR,//超出该范围时发生警报

	//Align分割Morp相关
	E_PARA_ALIGN_PARTIAL_USE,	// USE OFF : 0 / ON : 1
	E_PARA_ALIGN_PARTIAL_THRESHOLD,//用于查找点亮区域
	E_PARA_ALIGN_PARTIAL_OUTER,//ROI区域OFFSET
	E_PARA_ALIGN_PARTIAL_LEFT_OFFSET,	// ROI LEFT OFFSET
	E_PARA_ALIGN_PARTIAL_RIGHT_OFFSET,	// ROI RIGHT OFFSET
	E_PARA_ALIGN_PARTIAL_TOP_OFFSET,	// ROI TOP OFFSET
	E_PARA_ALIGN_PARTIAL_BOTTOM_OFFSET,	// ROI BOTTOM OFFSET

	//与组相关
	E_PARA_GROUP_TEXT,//显示文本
	E_PARA_GROUP_FLAG,//是否启用组判定
	E_PARA_GROUP1_COUNT,//组1判定像素数
	E_PARA_GROUP1_DIAMETER,//组1判定直径
	E_PARA_GROUP1_DELETE,//删除组1
	E_PARA_GROUP2_COUNT,//组2判定像素数
	E_PARA_GROUP2_DIAMETER,//组2判定直径
	E_PARA_GROUP2_DELETE,//删除组2
	E_PARA_GROUP3_COUNT,//组3判定像素数
	E_PARA_GROUP3_DIAMETER,//组3判定直径
	E_PARA_GROUP3_DELETE,//删除组3

	//临时关联Pad浮点
	E_PARA_PAD_BRIGHT_TEXT,//显示文本
	E_PARA_PAD_BRIGHT_FLAG,//Pad浮点
	E_PARA_PAD_BRIGHT_X,//Pad浮点宽度
	E_PARA_PAD_BRIGHT_Y,//Pad浮点深度

	//出现混色较多->倾向于与无名点相似(数量较多时判定ET)
	E_PARA_HS_JUDGMENT_TEXT,//显示文本
	E_PARA_HS_JUDGMENT_COUNT_BRIGHT,//设置数量
	E_PARA_HS_JUDGMENT_COUNT_DARK,//设置数量

	//在潮湿的江西人性不良附近存在积分过检
	E_PARA_STRONG_DEFECT_NOISE_TEXT,//显示文本
	E_PARA_STRONG_DEFECT_NOISE_ADJUST_RANGE,//清除不良的扩展范围

	//PCD_CRACK:如果在非检查区域内存在线路不良,则修改不良名称
	E_PARA_PCD_CRACK_TEXT,//显示文本
	E_PARA_PCD_CRACK_FLAG,//是否使用PCD CRACK

	// Non Insp Area
	E_PARA_NON_INSP_AREA_TEXT,//显示文本
	E_PARA_NON_INSP_AREA_ONLY_LINE,//仅在线路不良时才有效

	//Dimple判定Ratio
	E_PARA_DIMPLE_RATIO_TEXT,//显示文本
	E_PARA_DIMPLE_RATIO_GRAY_Active,//DIMPLE判定Ratio Active
	E_PARA_DIMPLE_RATIO_GRAY_Edge,//DIMPLE判定Ratio Edge
	E_PARA_DIMPLE_RATIO_RGB,//判定DIMPLE

	//在限制内删除Spot Ratio
	E_PARA_SISPOT_TEXT,//显示文本
	E_PARA_SISPOT_RATIO_ACTIVE,//ACTIVE SPOT判定RATIO设置为当前1
	E_PARA_SISPOT_RATIO_EDGE,//EDGE SPOT判定RATIO设置为当前1
	E_PARA_SISPOT_NUMBER_GVCOUNT,	// GV COUNT
	E_PARA_SISPOT_AREA,	// GV COUNT

	//删除限制内强诗人Spot Ratio
	E_PARA_STRONG_SISPOT_TEXT,//显示文本
	E_PARA_STRONG_SISPOT_RATIO_ACTIVE,//ACTIVE SPOT判定RATIO设置为当前1
	E_PARA_STRONG_SISPOT_RATIO_EDGE,//EDGE SPOT判定RATIO设置为当前1
	E_PARA_STRONG_SISPOT_NUMBER_GVCOUNT,	// GV COUNT
	E_PARA_STRONG_SISPOT_AREA,	// GV COUNT

	//暗点确认Logic
	E_PARA_DUST_DARKPOINT_TEXT,//显示文本
	E_PARA_DUST_DARKPOINT_ONOFF,//ACTIVE SPOT判定RATIO设置为当前1

	// Camera Tap Overkill Delet
	E_PARA_CAMERA_TAP_OVERKILL_TEXT,//显示文本
	E_PARA_CAMERA_TAP_OVERKILL_ONOFF,//显示文本
	E_PARA_CAMERA_TAP_OVERKILL_CAMERATYPE,	// ㅋㅋ
	E_PARA_CAMERA_TAP_OVERKILL_OFFSET,//显示文本

	//Norch部门Overkill Delet
	E_PARA_NORCH_OVERKILL_TEXT,	// 
	E_PARA_NORCH_OVERKILL_ONOFF,	// 
	E_PARA_NORCH_OVERKILL_UNIT_X,	// 
	E_PARA_NORCH_OVERKILL_UNIT_Y,	// 
	E_PARA_NORCH_OVERKILL_THGV_GREEN,	// 
	E_PARA_NORCH_OVERKILL_THGV_RB,	// 
	E_PARA_NORCH_OVERKILL_ABS_GREEN,	// 
	E_PARA_NORCH_OVERKILL_ABS_RB,	// 
	E_PARA_NORCH_OVERKILL_OFFSET,	//

	E_PARA_LASTGROUP_JUDGE_TEXT,
	E_PARA_LASTGROUP_JUDGE_ALL_COUNT,
	E_PARA_LASTGROUP_JUDGE_BRIGHT_COUNT,
	E_PARA_LASTGROUP_JUDGE_DARK_COUNT,

	// Mura Normal Classification Parameter
	E_PARA_MURANORMAL_CLASSPARA_TEXT,	//
	E_PARA_MURANORMAL_CLASSPARA_TYPE1,	//
	E_PARA_MURANORMAL_CLASSPARA_TYPE2,	//
	E_PARA_MURANORMAL_CLASSPARA_TYPE3,	//
	E_PARA_MURANORMAL_CLASSPARA_TYPE4,	//

	// Mura Normal 2nd Judgement OverKill Reduction (T3)
	E_PARA_MURANORMAL_OR_TEXT,	//
	E_PARA_MURANORMAL_OR_TYPE3_BBS_DIFFGV,	//
	E_PARA_MURANORMAL_OR_TYPE3_SBS_DIFFGV,	//
	E_PARA_MURANORMAL_OR_TYPE3_CH_DIFFGV,	//
	E_PARA_MURANORMAL_OR_TYPE3_BUBBLEMERGE,	//

	//Point-point重复数据删除offset
	E_PARA_Duplicate_offset,

	//
		//图像旋转相关
	E_PARA_IMAGE_ROTATE_TEXT,//显示文本
	E_PARA_IMAGE_ROTATE,

	//添加B11DICS
	E_PARA_AVI_DICS_TEXT,    // DICS Contrast Pram
	E_PARA_AVI_DICS_IMAGE_RATIO,//存储图像比例//
	E_PARA_AVI_DICS_GAUSSIAN_SIZE,    // Gaussian Size // 2022.06.24 
	E_PARA_AVI_DICS_GAUSSIAN_SIGMA,    // Gaussian sigma // 2022.06.24 
	E_PARA_AVI_DICS_CONTRAST_COUNT,    // COUNT
	E_PARA_AVI_DICS_CONTRAST_MIN_OFFSET,    // MIN OFFSET
	E_PARA_AVI_DICS_CONTRAST_MAX_OFFSET,    // MAX OFFSET

	E_PARA_AVI_DICS_SHIFTRANGE_DUST,//用于Shift Copy
	E_PARA_AVI_DICS_GAUSSIAN_SIZE_DUST,    // Gaussian Size // 2022.06.24 
	E_PARA_AVI_DICS_GAUSSIAN_SIGMA_DUST,    // Gaussian sigma // 2022.06.24 
	E_PARA_AVI_DICS_MAX_FILTER_SIZE_DUST,    // Max filter Size
	E_PARA_AVI_DICS_AI_CROP_EXPAND,    // AI Crop expand 2023/08/03

	//G3的Parameta客户请求
	//E_PARA_AVI_DICS_GAUSSIAN_SIZE_G3,    // Gaussian Size	//
	//E_PARA_AVI_DICS_GAUSSIAN_SIGMA_G3,    // Gaussian sigma	//
	//E_PARA_AVI_DICS_CONTRAST_COUNT_G3,    // COUNT			//
	//E_PARA_AVI_DICS_CONTRAST_MIN_OFFSET_G3,    // MIN OFFSET		//
	//E_PARA_AVI_DICS_CONTRAST_MAX_OFFSET_G3,    // MAX OFFSET		//

	E_PARA_AVI_LablePol_Text,
	E_PARA_AVI_Label_Flag,    //yuxuefe for Mark
	E_PARA_AVI_PolNum_Flag,    //yuxuefei for Mark
	E_PARA_AVI_PolSign_Flag,
	E_PARA_AVI_Pol_Save_Template,	// 是否保存模版
	E_PARA_AVI_PolNum_ID,			// PolNum 模版ID
	E_PARA_AVI_PolSign_ID,			// PolSign 模版ID
	E_PARA_AVI_Label_Width,			// 标签宽度
	E_PARA_AVI_Label_Height,		// 标签宽度
	E_PARA_AVI_PolNum_MinWidth,		// PolNum 最小宽度
	E_PARA_AVI_PolNum_MaxWidth,		// PolNum 最大宽度
	E_PARA_AVI_PolNum_MinHeight,	// PolNum 最小高度
	E_PARA_AVI_PolNum_MaxHeight,	// PolNum 最大高度
	E_PARA_AVI_PolSign_MinWidth,	// PolSign 最小宽度
	E_PARA_AVI_PolSign_MaxWidth,	// PolSign 最大宽度
	E_PARA_AVI_PolSign_MinHeight,	// PolSign 最小高度
	E_PARA_AVI_PolSign_MaxHeight,	// PolSign 最大高度
	E_PARA_AVI_Label_Threshold,		// Label 二值化阈值
	E_PARA_AVI_PolNum_Threshold,	// PolNum 二值化阈值
	E_PARA_AVI_PolSign_Threshold,	// PolSign 二值化阈值
	E_PARA_AVI_PolCell_Size,		// 灯珠大小，填充polmark用
	E_PARA_AVI_Rotate_Image,		// 是否启用矫正
	E_PARA_AVI_White_Number,		// yuxuefei
	E_PARA_AVI_ZARA_Number,			//yuxuefei
	E_PARA_AVI_DENSE_ZARA_Number,   //yuxuefei
	E_PARA_AVI_DENSE_ZARA_Distance, //yuxuefei

	///////////////////////////////// SVI

		//与AD GV相关(亮度检查)
	E_PARA_SVI_CHECK_MIN_GV = 0,//模式平均GV最小亮度
	E_PARA_SVI_CHECK_MAX_GV,//模式平均GV最大亮度

	///////////////////////////////////////////////////////////////////////////////////////////////

		//AD相关
	E_PARA_SVI_AD_TEXT = 0,//显示文本
	E_PARA_SVI_AD_IMAGE_NUM,//AD要检查的模式号(E_IMAGE_CLASSIFY_AVI_WHITE:4)
	E_PARA_SVI_AD_RATE,//匹配率(如果禁用:0)
	E_PARA_SVI_AD_ZOOM,//画面缩放比例
	E_PARA_SVI_AD_MIN_GV,//最小平均GV
	E_PARA_SVI_AD_MAX_GV,//最大平均GV
	E_PARA_SVI_AD_MAX_STD,//最大标准偏差

	// Size
	E_PARA_SVI_CELL_SIZE_TEXT,//显示文本
	E_PARA_SVI_CELL_COAX_SIZE_X,//同轴相机影像上的Cell横向长度(pixel)
	E_PARA_SVI_CELL_COAX_SIZE_Y,//同轴相机影像上的Cell深度长度(pixel)
	E_PARA_SVI_CELL_SIDE_SIZE_X,//侧摄像头画面中的Cell横向长度(pixel)
	E_PARA_SVI_CELL_SIDE_SIZE_Y,//侧摄像头图像上的Cell深度长度(pixel)

	//Align相关
	E_PARA_SVI_ALIGN_TEXT,//显示文本
	E_PARA_SVI_ALIGN_THRESHOLD,//二进制

	//Round Cell相关
	E_PARA_SVI_ROUND_TEXT,//显示文本
	E_PARA_SVI_ROUND_USE,//使用Round拐角处查找算法有/无
	E_PARA_SVI_ROUND_IN,//Round拐角处内侧排除检查区域
	E_PARA_SVI_ROUND_SIZE,//设置Round区域范围
	E_PARA_SVI_ROUND_DIAGONAL,//设置Round区域拐角

	E_PARA_SVI_CROP_RATIO,

	//添加B11DICS
	E_PARA_SVI_DICS_TEXT,//DICS Contrast Pram//0:禁用,1:Auto模式(AVI,SVI存储驱动器不同),2:Menual模式(保存D驱动器)
	E_PARA_SVI_CONTRAST_COUNT,    // COUNT
	E_PARA_SVI_CONTRAST_MIN_OFFSET,    // MIN OFFSET
	E_PARA_SVI_CONTRAST_MAX_OFFSET,    // MAX OFFSET

	E_PARA_SVI_TOTAL_COUNT,	// Total

	///////////////////////////// APP

	//Curl
	E_PARA_APP_CURL_TEXT = 0,//显示文本
	E_PARA_APP_CURL_USE,//使用Curl Algorithm
	E_PARA_APP_CURL_RANGE_X,//平均配置文件的数量
	E_PARA_APP_CURL_RANGE_Y_TOP,//提取Profile的范围尺寸TOP
	E_PARA_APP_CURL_RANGE_Y_BOTTOM,//提取配置文件的范围尺寸BOTTOM
	E_PARA_APP_CURL_IMAGE_NUM,//Curl Algorithm使用的Image number
	E_PARA_APP_CURL_CONDITION_COUNT,//当大于平均Size的Size大于多少时,判断为Curl
	E_PARA_APP_CURL_SEARCH_RATIO,//将平均Size的几倍判定为Curl
	E_PARA_APP_CURL_STANDARD_GV_RATIO,//在Curl开始的基准上下降百分之几进行测量
	E_PARA_APP_CURL_CORNER_SEARCH_COUNT,//Corner部分的Curl Parameter,大于平均Size的Size大于多少时,将判断为Curl
	E_PARA_APP_CURL_CORNER_SEARCH_RATIO,//将Corner部分的Curl Parameter,平均Size的几倍判定为Curl
	E_PARA_APP_CURL_BLUR_SIZE,	// Blur Mask Size
	E_PARA_APP_CURL_GAUSSIGMA,//画面中的Cell垂直长度(pixel)
	E_PARA_APP_CURL_START_OFFSET_LEFT,//用于排除C-Cut部分的检测起点Offset
	E_PARA_APP_CURL_END_OFFSET_RIGHT,//用于排除C-Cut部分的检测端点Offset
	E_PARA_APP_CURL_PROFILE_SEARCH_OFFSET,//在Profile中使用最小值后的Offset大小作为宽度保留值
	E_PARA_APP_RESERVE2,
	E_PARA_APP_RESERVE3,
	E_PARA_APP_PAD_EDGE_TEXT,
	E_PARA_APP_PAD_EDGE_THETA,

	//AD Check
	E_PARA_APP_AD_TEXT,//显示文本
	E_PARA_APP_AD_IMAGE_NUM,//要使用AD Check的Image
	E_PARA_APP_AD_BLUR_SIZE,	// Blur Size
	E_PARA_APP_AD_THRESHOLD,//二进制值
	E_PARA_APP_AD_LIMIT_AREA,//二进制画面中必须存在的最小大小条件
	E_PARA_APP_AD_GV,//AD Check GV值

	//Align相关
	E_PARA_APP_ALIGN_TEXT,//显示文本
	E_PARA_APP_ALIGN_THRESHOLD,//二进制值
	E_PARA_APP_ALIGN_DILATE,//用于二进制后留下最大Blob的膨胀
	E_PARA_APP_ALIGN_PANEL_EDGE_THETA,//Cell外围Edge检测标准Theta
	E_PARA_APP_ALIGN_ANGLE_ERR,//如果超出该范围,将出现中警报
	E_PARA_APP_ALIGN_ANGLE_WAR,//超出该范围时发生警报
	E_PARA_APP_ALIGN_AVG_OFFSET,
	E_PARA_APP_ALIGN_USE_OVERRANGE,//Align后是否超出Pannel Size范围
	E_PARA_APP_ALIGN_RANGE_OVER,//Align后,如果Pannel Size超出范围,AD将被不良处理

	//关于Polygon区域处理
	E_PARA_APP_POLYGON_TEXT,//显示文本
	E_PARA_APP_MAKE_ACTIVE_MASK,//创建Polygon Mask Flag
	E_PARA_APP_POLYGON_IMAGE_NUM,//ROUND处理时使用的图像
	E_PARA_APP_POLYGON_RESIZE,//Resize的画面大小
	E_PARA_APP_POLYGON_GAUS_SIZE,//Gaussian Blur Mask大小
	E_PARA_APP_POLYGON_GAUS_SIGMA,//Gaussian Blur Sigma大小
	E_PARA_APP_POLYGON_THRESHOLD,//提取Edge后使用的二进制值
	E_PARA_APP_POLYGON_OPEN_SIZE,//开放计算Mask大小
	E_PARA_APP_POLYGON_SELECT_BLOB,//在降序的Blob中选择第几大
	E_PARA_APP_POLYGON_DILATE_SIZE,//Dilate运算Mask大小
	E_PARA_APP_POLYGON_ERODE_SIZE,//Erode运算Mask大小
	E_PARA_APP_POLYGON_CORNER_ROI_SIZE,//使用Corner区域的ROI大小
	E_PARA_APP_POLYGON_BM_THETA_LT,//BM Line Search的基准角度
	E_PARA_APP_POLYGON_BM_THETA_RB,
	E_PARA_APP_POLYGON_BM_IGNORE_GV,//BM Line搜索基准角度点的最小GV值条件
	E_PARA_APP_POLYGON_BM_PRE_THRESH_RATIO,//在留下BM Line Blob之前,在Threshold过程中使用的平均值中使用的百分比,以消除其他杂乱的Blob
	E_PARA_APP_ADGV_TEXT,	//ADGV TEXT
	E_PARA_APP_ADGV_MEAN_GV,//基于ADGV的平均GV
	E_PARA_APP_RESERVE27,
	E_PARA_APP_RESERVE28,
	E_PARA_APP_RESERVE29,
	E_PARA_APP_RESERVE30,
	E_PARA_APP_RESERVE31,
	E_PARA_APP_RESERVE32,
	E_PARA_APP_RESERVE33,
	E_PARA_APP_RESERVE34,

	// Align Area
	E_PARA_ALIGN_AREA_ACTIVE_L,	// 
	E_PARA_ALIGN_AREA_ACTIVE_R,	// 
	E_PARA_ALIGN_AREA_ACTIVE_T,	// 
	E_PARA_ALIGN_AREA_ACTIVE_B,	// 
	E_PARA_ALIGN_AREA_PAD_WIDTH,	// 
	E_PARA_ALIGN_AREA_PAD_LOCATION,	// 

	E_PARA_TOTAL_COUNT							// Total
};

#endif