/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_image_ImageProcessor */

#ifndef _Included_com_image_ImageProcessor
#define _Included_com_image_ImageProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_image_ImageProcessor
 * Method:    resizeImage
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_image_ImageProcessor_resizeImage
  (JNIEnv *, jobject, jstring, jstring, jint, jint);

/*
 * Class:     com_image_ImageProcessor
 * Method:    toGrayImage
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_image_ImageProcessor_toGrayImage
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
