/**
 * @FilePath     : /pcl_test/src/test_7.cpp
 * @Description  : 离线读取保存数据进行检测（不依赖网线直连设备）
 * @Author       : generated by GitHub Copilot
 * @Date         : 2026-03-23
 * @Version      : 0.0.1
 * @Copyright (c) 2026 by G, All Rights Reserved.
 **/

#include "rsldSDK.h"
#include <filesystem>
#include <string>


#include "ox_d.h"
#include "ox_seg.h"
#include <pcl/console/parse.h>
#include <pcl/console/print.h>
#include <pcl/console/time.h>
#include <pcl/filters/median_filter.h>
#include <pcl/filters/radius_outlier_removal.h>
#include <pcl/filters/random_sample.h>
#include <pcl/filters/statistical_outlier_removal.h>
#include <pcl/filters/voxel_grid.h>
#include <pcl/io/pcd_io.h>
#include <pcl/io/ply_io.h>


#include <cfloat>
#include <chrono>
#include <iomanip>
#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/opencv.hpp>
#include <pcl/common/common.h>
#include <pcl/common/pca.h>
#include <pcl/common/transforms.h>
#include <pcl/features/impl/moment_of_inertia_estimation.hpp>

#define TICK(x) auto bench_##x = std::chrono::high_resolution_clock::now();
#define TOCK(x) std::cout << #x ": " << std::chrono::duration_cast<std::chrono::microseconds>(std::chrono::high_resolution_clock::now() - bench_##x).count() << "us" << std::endl;

static const std::vector<std::string> CLASS_NAMES = {"person", "bicycle", "car",     "motorcycle", "airplane",   "bus",       "train",    "truck",    "boat",     "traffic light", "fire hydrant", "stop sign",   "parking meter", "bench",        "bird",           "cat",        "dog",          "horse",         "sheep",        "cow",        "elephant",
                                                     "bear",   "zebra",   "giraffe", "backpack",   "umbrella",   "handbag",   "tie",      "suitcase", "frisbee",  "skis",          "snowboard",    "sports ball", "kite",          "baseball bat", "baseball glove", "skateboard", "surfboard",    "tennis racket", "bottle",       "wine glass", "cup",
                                                     "fork",   "knife",   "spoon",   "bowl",       "banana",     "apple",     "sandwich", "orange",   "broccoli", "carrot",        "hot dog",      "pizza",       "donut",         "cake",         "chair",          "couch",      "potted plant", "bed",           "dining table", "toilet",     "tv",
                                                     "laptop", "mouse",   "remote",  "keyboard",   "cell phone", "microwave", "oven",     "toaster",  "sink",     "refrigerator",  "book",         "clock",       "vase",          "scissors",     "teddy bear",     "hair drier", "toothbrush"};

static const std::vector<std::vector<unsigned int>> COLORS = {{0, 114, 189},   {217, 83, 25},   {237, 177, 32},  {126, 47, 142}, {119, 172, 48},  {77, 190, 238},  {162, 20, 47},   {76, 76, 76},  {153, 153, 153}, {255, 0, 0},     {255, 128, 0},   {191, 191, 0},   {0, 255, 0},     {0, 0, 255},    {170, 0, 255},  {85, 85, 0},
                                                              {85, 170, 0},    {85, 255, 0},    {170, 85, 0},    {170, 170, 0},  {170, 255, 0},   {255, 85, 0},    {255, 170, 0},   {255, 255, 0}, {0, 85, 128},    {0, 170, 128},   {0, 255, 128},   {85, 0, 128},    {85, 85, 128},   {85, 170, 128}, {85, 255, 128}, {170, 0, 128},
                                                              {170, 85, 128},  {170, 170, 128}, {170, 255, 128}, {255, 0, 128},  {255, 85, 128},  {255, 170, 128}, {255, 255, 128}, {0, 85, 255},  {0, 170, 255},   {0, 255, 255},   {85, 0, 255},    {85, 85, 255},   {85, 170, 255},  {85, 255, 255}, {170, 0, 255},  {170, 85, 255},
                                                              {170, 170, 255}, {170, 255, 255}, {255, 0, 255},   {255, 85, 255}, {255, 170, 255}, {85, 0, 0},      {128, 0, 0},     {170, 0, 0},   {212, 0, 0},     {255, 0, 0},     {0, 43, 0},      {0, 85, 0},      {0, 128, 0},     {0, 170, 0},    {0, 212, 0},    {0, 255, 0},
                                                              {0, 0, 43},      {0, 0, 85},      {0, 0, 128},     {0, 0, 170},    {0, 0, 212},     {0, 0, 255},     {0, 0, 0},       {36, 36, 36},  {73, 73, 73},    {109, 109, 109}, {146, 146, 146}, {182, 182, 146}, {219, 219, 219}, {0, 114, 189},  {80, 183, 189}, {128, 128, 0}};

static const std::vector<std::vector<unsigned int>> MASK_COLORS = {{255, 56, 56},  {255, 157, 151}, {255, 112, 31}, {255, 178, 29},  {207, 210, 49}, {72, 249, 10},  {146, 204, 23}, {61, 219, 134}, {26, 147, 52},   {0, 212, 187},
                                                                   {44, 153, 168}, {0, 194, 255},   {52, 69, 147},  {100, 115, 255}, {0, 24, 236},   {132, 56, 255}, {82, 0, 133},   {203, 56, 255}, {255, 149, 200}, {255, 55, 199}};

struct ObjectOBB
{
    int                                    object_id;
    pcl::PointXYZRGB                       position;
    Eigen::Matrix3f                        rotation;
    Eigen::Vector3f                        dimensions;
    pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloud;
};

ImageData matToImageData(const cv::Mat& mat, PixelFormat format)
{
    ImageData img;
    img.width       = mat.cols;
    img.height      = mat.rows;
    img.format      = format;
    //img.stride      = mat.step[0];   // bytes per row
    img.channels    = 1;
    size_t dataSize = img.height * img.width *2;
    img.data        = new uint8_t[dataSize];
    memcpy(img.data, mat.data, dataSize);
    return img;
}

void testOBBComputationWithParams(const pcl::PointCloud<pcl::PointXYZRGB>::Ptr& original_cloud, int object_id)
{
    std::cout << "\n========================================================" << std::endl;
    std::cout << "Testing Object ID: " << object_id << " | Original Points: " << original_cloud->size() << std::endl;
    std::cout << "--------------------------------------------------------" << std::endl;
    std::cout << std::left << std::setw(15) << "Sample Count" << std::setw(15) << "Method" << std::setw(15) << "Points Left" << std::setw(15) << "Time (us)" << std::setw(30) << "Dimensions (x, y, z)" << std::setw(30) << "Position (x, y, z)" << std::endl;
    std::cout << "--------------------------------------------------------" << std::endl;

    std::vector<unsigned int> sample_counts = {0, 500, 1000, 2000, 5000, 7000, 10000, 13000, 15000};

    for (unsigned int sample_count : sample_counts) {
        pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloud_to_use(new pcl::PointCloud<pcl::PointXYZRGB>);

        if (sample_count > 0 && sample_count < original_cloud->size()) {
            pcl::RandomSample<pcl::PointXYZRGB> ran;
            ran.setInputCloud(original_cloud);
            ran.setSample(sample_count);
            ran.filter(*cloud_to_use);

            if (cloud_to_use->size() < 10) {
                continue;
            }
        }
        else {
            cloud_to_use = original_cloud;
        }

        std::string sample_str = (sample_count == 0) ? "Original" : std::to_string(sample_count);

        auto                                             start_moie = std::chrono::high_resolution_clock::now();
        pcl::MomentOfInertiaEstimation<pcl::PointXYZRGB> feature_extractor;
        feature_extractor.setInputCloud(cloud_to_use);
        feature_extractor.compute();
        pcl::PointXYZRGB min_pt_moie, max_pt_moie, position_moie;
        Eigen::Matrix3f  rotation_moie;
        feature_extractor.getOBB(min_pt_moie, max_pt_moie, position_moie, rotation_moie);
        auto end_moie      = std::chrono::high_resolution_clock::now();
        auto duration_moie = std::chrono::duration_cast<std::chrono::microseconds>(end_moie - start_moie).count();

        Eigen::Vector3f   dim_moie(max_pt_moie.x - min_pt_moie.x, max_pt_moie.y - min_pt_moie.y, max_pt_moie.z - min_pt_moie.z);
        std::stringstream d_moie, p_moie;
        d_moie << std::fixed << std::setprecision(3) << dim_moie.x() << ", " << dim_moie.y() << ", " << dim_moie.z();
        p_moie << std::fixed << std::setprecision(3) << position_moie.x << ", " << position_moie.y << ", " << position_moie.z;
        std::cout << std::left << std::setw(15) << sample_str << std::setw(15) << "MoIE (PCL)" << std::setw(15) << cloud_to_use->size() << std::setw(15) << duration_moie << std::setw(30) << d_moie.str() << std::setw(30) << p_moie.str() << std::endl;

        auto            start_pca = std::chrono::high_resolution_clock::now();
        Eigen::Vector4f pcaCentroid;
        pcl::compute3DCentroid(*cloud_to_use, pcaCentroid);
        Eigen::Matrix3f covariance;
        pcl::computeCovarianceMatrixNormalized(*cloud_to_use, pcaCentroid, covariance);
        Eigen::SelfAdjointEigenSolver<Eigen::Matrix3f> eigen_solver(covariance, Eigen::ComputeEigenvectors);
        Eigen::Matrix3f                                eigenVectorsPCA = eigen_solver.eigenvectors();
        Eigen::Vector3f                                eigenValuesPCA  = eigen_solver.eigenvalues();
        eigenVectorsPCA.col(2)                                         = eigenVectorsPCA.col(0).cross(eigenVectorsPCA.col(1));

        Eigen::Matrix4f projectionTransform(Eigen::Matrix4f::Identity());
        projectionTransform.block<3, 3>(0, 0) = eigenVectorsPCA.transpose();
        projectionTransform.block<3, 1>(0, 3) = -1.f * (projectionTransform.block<3, 3>(0, 0) * pcaCentroid.head<3>());
        pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloudPointsProjected(new pcl::PointCloud<pcl::PointXYZRGB>);
        pcl::transformPointCloud(*cloud_to_use, *cloudPointsProjected, projectionTransform);

        pcl::PointXYZRGB minPoint, maxPoint;
        pcl::getMinMax3D(*cloudPointsProjected, minPoint, maxPoint);
        Eigen::Vector3f meanDiagonal = 0.5f * (maxPoint.getVector3fMap() + minPoint.getVector3fMap());

        Eigen::Vector3f position_pca = eigenVectorsPCA * meanDiagonal + pcaCentroid.head<3>();
        Eigen::Vector3f dim_pca      = maxPoint.getVector3fMap() - minPoint.getVector3fMap();

        auto end_pca      = std::chrono::high_resolution_clock::now();
        auto duration_pca = std::chrono::duration_cast<std::chrono::microseconds>(end_pca - start_pca).count();

        std::stringstream d_pca, p_pca;
        d_pca << std::fixed << std::setprecision(3) << dim_pca.x() << ", " << dim_pca.y() << ", " << dim_pca.z();
        p_pca << std::fixed << std::setprecision(3) << position_pca.x() << ", " << position_pca.y() << ", " << position_pca.z();

        std::cout << std::left << std::setw(15) << sample_str << std::setw(15) << "PCA (Fast)" << std::setw(15) << cloud_to_use->size() << std::setw(15) << duration_pca << std::setw(30) << d_pca.str() << std::setw(30) << p_pca.str() << std::endl;
        std::cout << "  " << std::endl;
    }
}

int test_saved_data_seg_pointcloud(int argc, char** argv)
{
    std::string model_path = "E:/test/pcl_test/model/yolov8m-seg.onnx";
    std::string color_path = "E:/test/pcl_test/data/RightSensor_Viewer/savedata_2/color/color_00001.png";
    std::string ply_dir    = "E:/test/pcl_test/data/RightSensor_Viewer/savedata_2/3D/pointcloud.ply";

    if (argc > 1) {
        color_path = argv[1];
    }
    if (argc > 2) {
        ply_dir = argv[2];
    }
    if (argc > 3) {
        model_path = argv[3];
    }

    cv::Mat color_img = cv::imread(color_path);
    if (color_img.empty()) {
        std::cerr << "Failed to open color image: " << color_path << std::endl;
        return -1;
    }

    auto            detector = std::make_unique<YOLOv8SegDetector>(model_path, false, 0.3f, 0.6f);
    DetectionResult result   = detector->Detect(color_img);
    std::cout << "Detection result: " << result.boxes.size() << " objects" << std::endl;
    cv::Mat          visual = color_img.clone();
    std::vector<int> person_indices;


    std::vector<Point2i> objPixels;
    cv::Mat              locations;



    for (size_t i = 0; i < result.boxes.size(); ++i) {
        int class_id = (i < result.class_ids.size()) ? result.class_ids[i] : -1;
        if (class_id == 0) {
            person_indices.push_back((int)i);
            cv::Mat mask = result.masks[i];
            if (mask.size() != color_img.size()) {
                cv::resize(mask, mask, color_img.size(), 0, 0, cv::INTER_NEAREST);
            }
            cv::Mat        mask_cropped = cv::Mat::zeros(color_img.size(), CV_8UC1);
            cv::Rect_<int> roi_int      = result.boxes[i];
            cv::Rect       roi          = roi_int & cv::Rect(0, 0, color_img.cols, color_img.rows);
            if (roi.width > 0 && roi.height > 0) {
                mask(roi).copyTo(mask_cropped(roi));
                mask_cropped   = mask_cropped * 255;
                cv::Mat kernel = cv::getStructuringElement(cv::MORPH_RECT, cv::Size(5, 5));   // 7x7核约等于向内腐蚀3个像素
                cv::erode(mask_cropped, mask_cropped, kernel);
            }
            cv::findNonZero(mask_cropped, locations);
            if (!locations.empty()) {
                objPixels.resize(locations.total());
                std::memcpy(objPixels.data(), locations.data, locations.total() * sizeof(Point2i));
            }
            cv::rectangle(visual, result.boxes[i], cv::Scalar(0, 255, 0), 2);
        }
    }

    cv::imwrite("./test_7_detection_result.png", visual);
    std::cout << "Saved visual result to test_7_detection_result.png" << std::endl;
    //std::cout << "Reading PLY clouds from: " << ply_dir << std::endl;


    // 点云读取
    // pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZRGB>);
    // if (pcl::io::loadPLYFile(ply_dir, *cloud) != 0) {
    //    std::cerr << "Failed to load PLY file: " << ply_dir << std::endl;
    //    return 0;
    //}
    // if (cloud->empty()) {
    //    std::cout << "Ignore empty cloud: " << ply_dir << std::endl;
    //    return 0;
    //}
    // std::cout << "Loaded cloud " << ply_dir << " (" << cloud->size() << " points)" << std::endl;



    void*     receiver1 = CreateInterface(600, 800);
    //uint8_t*  depthdata = new uint8_t[800 * 600 * 2];
    ImageData imgDepthReg;
    //imgDepthReg.data = depthdata;
    //memset(depthdata, 0, 800 * 600 * 2);
    //imgDepthReg.width       = 0;
    std::string deepth_path = "E:/test/pcl_test/data/RightSensor_Viewer/savedata_2/2D/depth_00001.png";
    std::string xmlpath     = "E:\\test\\pcl_test\\config\\calib_color_readFromCamera2.yaml";
    cv::Mat     depth_mat   = cv::imread(deepth_path, cv::IMREAD_UNCHANGED);
    if (depth_mat.empty() || depth_mat.type() != CV_16UC1) {
        std::cerr << "Failed to load depth image or wrong type" << std::endl;
        return -1;
    }
    imgDepthReg = matToImageData(depth_mat, PixelFormat::RGB8);

    std::vector<pointxyzrgb> person_points;
    ImageData*               rgbd_placeholder = nullptr;
    std::vector<Point2i>     rgbindexes_placeholder;

    if (!objPixels.empty()) {
        getObjectPoints(receiver1, objPixels, imgDepthReg, xmlpath, person_points, rgbd_placeholder, rgbindexes_placeholder);   // 6. 调用SDK接口获取点云
        if (!person_points.empty()) {

            pcl::PointCloud<pcl::PointXYZRGB>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZRGB>);
            cloud->width    = person_points.size();
            cloud->height   = 1;
            cloud->is_dense = false;
            cloud->points.resize(cloud->width * cloud->height);
            for (size_t k = 0; k < person_points.size(); ++k) {
                cloud->points[k].x = person_points[k].x;
                cloud->points[k].y = person_points[k].y;
                cloud->points[k].z = person_points[k].z;
                cloud->points[k].r = person_points[k].r;
                cloud->points[k].g = person_points[k].g;
                cloud->points[k].b = person_points[k].b;
            }
            // 处理测试
            // float min_dist2   = FLT_MAX;
            // int   nearest_idx = -1;
            // float sum_x = 0, sum_y = 0, sum_z = 0;
            // for (size_t kk = 0; kk < cloud->points.size(); ++kk) {
            //    const auto& p = cloud->points[kk];
            //    if (!std::isfinite(p.x) || !std::isfinite(p.y) || !std::isfinite(p.z))
            //        continue;
            //    sum_x += p.x;
            //    sum_y += p.y;
            //    sum_z += p.z;
            //}
            // sum_x /= cloud->points.size();
            // sum_y /= cloud->points.size();
            // sum_z /= cloud->points.size();

            // pcl::PointCloud<pcl::PointXYZRGB>::Ptr filtered_cloud(new pcl::PointCloud<pcl::PointXYZRGB>);
            // if (std::abs(sum_z) >= 0) {
            //     const float keep_radius = 1.f;
            //     for (const auto& p : cloud->points) {
            //         if (!std::isfinite(p.x) || !std::isfinite(p.y) || !std::isfinite(p.z))
            //             continue;
            //         float dz = p.z - sum_z;
            //         if (dz <= keep_radius) {
            //             filtered_cloud->push_back(p);
            //         }
            //     }
            // }

            //// 在进行一次`
            // sum_x = 0;
            // sum_y = 0;
            // sum_z = 0;
            // for (size_t kk = 0; kk < filtered_cloud->points.size(); ++kk) {
            //     const auto& p = filtered_cloud->points[kk];
            //     if (!std::isfinite(p.x) || !std::isfinite(p.y) || !std::isfinite(p.z))
            //         continue;
            //     sum_x += p.x;
            //     sum_y += p.y;
            //     sum_z += p.z;
            // }
            // sum_x /= filtered_cloud->points.size();
            // sum_y /= filtered_cloud->points.size();
            // sum_z /= filtered_cloud->points.size();

            //// 半径过滤
            // pcl::PointCloud<pcl::PointXYZRGB>::Ptr filtered_cloud_2(new pcl::PointCloud<pcl::PointXYZRGB>);
            // if (std::abs(sum_z) >= 0) {
            //     const float keep_radius = 0.5f;
            //     for (const auto& p : filtered_cloud->points) {
            //         if (!std::isfinite(p.x) || !std::isfinite(p.y) || !std::isfinite(p.z))
            //             continue;
            //         float dz = p.z - sum_z;
            //         if (dz <= keep_radius) {
            //             filtered_cloud_2->push_back(p);
            //         }
            //     }
            // }

            // 1) 计算每点到相机原点的距离
            struct DistPoint
            {
                float            dist;
                pcl::PointXYZRGB p;
            };
            std::vector<DistPoint> dist_pts;
            dist_pts.reserve(cloud->size());
            for (const auto& pt : cloud->points) {
                if (!std::isfinite(pt.x) || !std::isfinite(pt.y) || !std::isfinite(pt.z))
                    continue;
                float d2 = pt.x * pt.x + pt.y * pt.y + pt.z * pt.z;
                float d  = std::sqrt(d2);
                dist_pts.push_back({d, pt});
            }
            if (dist_pts.empty())
                return 0;   // 或 continue

            // 2) 排序：距离从小到大
            std::sort(dist_pts.begin(), dist_pts.end(), [](const DistPoint& a, const DistPoint& b) { return a.dist < b.dist; });

            // 计算距离直方图（大致分布）
            const float      bin_size = 0.1f;   // 每0.1米一个bin，更精细的分箱
            float            max_dist = dist_pts.back().dist;
            int              num_bins = static_cast<int>(std::ceil(max_dist / bin_size)) + 1;
            std::vector<int> dist_hist(num_bins, 0);
            for (const auto& dp : dist_pts) {
                int bin = static_cast<int>(dp.dist / bin_size);
                if (bin < num_bins) {
                    dist_hist[bin]++;
                }
            }
            std::cout << "\nDistance Histogram (meters, bin size 0.1m):" << std::endl;
            for (int i = 0; i < num_bins; ++i) {
                if (dist_hist[i] > 0) {
                    float bin_start = i * bin_size;
                    std::cout << std::fixed << std::setprecision(1) << bin_start << "m: " << dist_hist[i] << " points" << std::endl;
                }
            }
            std::cout << std::endl;

            // 使用OpenCV绘制直方图
            int     hist_width  = 800;
            int     hist_height = 600;
            cv::Mat hist_img(hist_height, hist_width, CV_8UC3, cv::Scalar(255, 255, 255));
            int     max_count = *std::max_element(dist_hist.begin(), dist_hist.end());
            if (max_count == 0)
                max_count = 1;   // 避免除零
            float scale_x = static_cast<float>(hist_width) / num_bins;
            float scale_y = static_cast<float>(hist_height - 50) / max_count;   // 留空间给标签

            for (int i = 0; i < num_bins; ++i) {
                int bar_height = static_cast<int>(dist_hist[i] * scale_y);
                int bar_x      = static_cast<int>(i * scale_x);
                int bar_width  = static_cast<int>(scale_x);
                cv::rectangle(hist_img, cv::Rect(bar_x, hist_height - bar_height - 50, bar_width, bar_height), cv::Scalar(0, 0, 255), -1);
            }

            // 添加轴标签
            cv::putText(hist_img, "Distance (m)", cv::Point(hist_width / 2 - 50, hist_height - 10), cv::FONT_HERSHEY_SIMPLEX, 0.5, cv::Scalar(0, 0, 0), 1);
            cv::putText(hist_img, "Count", cv::Point(10, 20), cv::FONT_HERSHEY_SIMPLEX, 0.5, cv::Scalar(0, 0, 0), 1);

            // 添加一些刻度
            for (int i = 0; i <= 10; ++i) {   // 每1米一个刻度
                int x = static_cast<int>((i / bin_size) * scale_x);
                if (x < hist_width) {
                    cv::line(hist_img, cv::Point(x, hist_height - 50), cv::Point(x, hist_height - 45), cv::Scalar(0, 0, 0), 1);
                    cv::putText(hist_img, std::to_string(i), cv::Point(x - 5, hist_height - 25), cv::FONT_HERSHEY_SIMPLEX, 0.4, cv::Scalar(0, 0, 0), 1);
                }
            }

            cv::imwrite("./distance_histogram.png", hist_img);
            std::cout << "Saved distance histogram to distance_histogram.png" << std::endl;

            // 4) 取前80%最近的点
            size_t keep_end   = (size_t)(dist_pts.size() * 0.9f);
            size_t keep_start = (size_t)(dist_pts.size() * 0.1f);
            if (keep_end < 1)
                keep_end = 1;
            pcl::PointCloud<pcl::PointXYZRGB>::Ptr kept_cloud(new pcl::PointCloud<pcl::PointXYZRGB>);
            kept_cloud->reserve(keep_end - keep_start);
            for (size_t i = keep_start; i < keep_end; ++i) {
                kept_cloud->push_back(dist_pts[i].p);
            }

            std::vector<pcl::PointCloud<pcl::PointXYZRGB>::Ptr> object_clouds;
            std::vector<int>                                    object_ids;
            if (kept_cloud->size() >= 10) {
                object_clouds.push_back(kept_cloud);
                // object_ids.push_back(i);
            }
            std::string all_filename = "./all_person_cloud_frame_sub.ply";
            pcl::io::savePLYFile(all_filename, *kept_cloud);


            // testOBBComputationWithParams(cloud, 0);
            std::cout << "Offline test completed." << std::endl;
        }
    }


    // 释放内存
    delete[] imgDepthReg.data;

    return 0;
}

int main(int argc, char** argv)
{
    return test_saved_data_seg_pointcloud(argc, argv);
}